In [ ]:
SHOW DATABASES;

Database
information_schema
mysql
performance_schema
sys
test

In [ ]:
CREATE DATABASE BUGBREW;

In [ ]:
USE BUGBREW;

In [ ]:
SELECT * FROM IRIS;

Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
1,5.1,3.5,1.4,0.2,Iris-setosa
2,4.9,3,1.4,0.2,Iris-setosa
3,4.7,3.2,1.3,0.2,Iris-setosa
4,4.6,3.1,1.5,0.2,Iris-setosa
5,5,3.6,1.4,0.2,Iris-setosa
6,5.4,3.9,1.7,0.4,Iris-setosa
7,4.6,NULL,1.4,0.3,Iris-setosa
8,5,3.4,1.5,0.2,Iris-setosa
9,4.4,2.9,1.4,0.2,Iris-setosa
10,4.9,3.1,1.5,0.1,Iris-setosa
11,5.4,3.7,1.5,0.2,Iris-setosa
12,4.8,3.4,1.6,0.2,Iris-setosa
13,4.8,3,1.4,0.1,Iris-setosa
14,4.3,3,1.1,0.1,
15,5.8,4,1.2,0.1,Iris-setosa
16,5.7,4.4,1.5,0.1,Iris-setosa
17,5.4,NULL,1.3,0.1,Iris-setosa
18,5.1,3.5,1.4,0.1,Iris-setosa
19,5.7,3.8,1.7,0.1,Iris-setosa
20,5.1,3.8,1.5,0.1,Iris-setosa
21,5.4,3.4,1.7,0.1,Iris-setosa
22,5.1,3.7,1.5,0.1,Iris-setosa
23,4.6,3.6,1,0.1,Iris-setosa
24,5.1,3.3,1.7,0.1,Iris-setosa
25,4.8,3.4,1.9,0.1,Iris-setosa
26,5,3,1.6,0.1,Iris-setosa
27,5,3.4,1.6,0.1,Iris-setosa
28,NULL,3.5,1.5,0.1,Iris-setosa
29,5.2,3.4,1.4,0.1,Iris-setosa
30,4.7,3.2,1.6,0.1,Iris-setosa
31,4.8,3.1,NULL,0.1,Iris-setosa
32,5.4,3.4,1.5,0.1,Iris-setosa
33,5.2,4.1,1.5,0.1,Iris-setosa
34,5.5,4.2,1.4,0.1,Iris-setosa
35,4.9,3.1,1.5,0.1,Iris-setosa
36,5,3.2,1.2,0.1,Iris-setosa
37,5.5,NULL,1.3,0.1,Iris-setosa
38,4.9,3.1,1.5,0.1,Iris-setosa
39,4.4,3,1.3,0.1,Iris-setosa
40,5.1,3.4,1.5,0.1,Iris-setosa
41,5,3.5,1.3,0.1,Iris-setosa
42,4.5,2.3,1.3,0.1,Iris-setosa
43,4.4,3.2,1.3,0.1,Iris-setosa
44,5,3.5,1.6,0.1,Iris-setosa
45,5.1,3.8,1.9,0.1,Iris-setosa
46,4.8,3,1.4,0.1,Iris-setosa
47,5.1,3.8,1.6,0.1,Iris-setosa
48,4.6,3.2,1.4,0.1,Iris-setosa
49,5.3,3.7,1.5,0.1,Iris-setosa
50,5,3.3,1.4,0.1,Iris-setosa
51,7,3.2,4.7,0.1,Iris-versicolor
52,6.4,3.2,4.5,0.1,Iris-versicolor
53,6.9,3.1,4.9,0.1,Iris-versicolor
54,5.5,2.3,4,0.1,Iris-versicolor
55,6.5,2.8,4.6,0.1,Iris-versicolor
56,5.7,2.8,4.5,0.1,Iris-versicolor
57,6.3,3.3,4.7,0.1,Iris-versicolor
58,4.9,2.4,3.3,0.1,Iris-versicolor
59,6.6,2.9,4.6,0.1,Iris-versicolor
60,5.2,2.7,3.9,0.1,Iris-versicolor
61,5,2,3.5,0.1,Iris-versicolor
62,5.9,3,4.2,0.1,Iris-versicolor
63,6,2.2,4,0.1,Iris-versicolor
64,6.1,2.9,4.7,0.1,Iris-versicolor
65,5.6,2.9,3.6,0.1,Iris-versicolor
66,6.7,3.1,4.4,0.1,Iris-versicolor
67,5.6,3,4.5,0.1,Iris-versicolor
68,5.8,2.7,4.1,0.1,Iris-versicolor
69,6.2,2.2,4.5,0.1,Iris-versicolor
70,5.6,2.5,3.9,0.1,Iris-versicolor
71,5.9,3.2,4.8,0.1,Iris-versicolor
72,6.1,2.8,4,0.1,Iris-versicolor
73,6.3,2.5,4.9,0.1,Iris-versicolor
74,6.1,2.8,4.7,0.1,Iris-versicolor
75,6.4,2.9,4.3,0.1,Iris-versicolor
76,6.6,3,4.4,0.1,Iris-versicolor
77,6.8,2.8,4.8,0.1,Iris-versicolor
78,6.7,3,5,0.1,Iris-versicolor
79,6,2.9,4.5,0.1,Iris-versicolor
80,5.7,2.6,3.5,0.1,Iris-versicolor
81,5.5,2.4,3.8,0.1,Iris-versicolor
82,5.5,2.4,3.7,0.1,Iris-versicolor
83,5.8,2.7,3.9,0.1,Iris-versicolor
84,6,2.7,5.1,0.1,Iris-versicolor
85,5.4,3,4.5,0.1,Iris-versicolor
86,6,3.4,4.5,0.1,Iris-versicolor
87,6.7,3.1,4.7,0.1,Iris-versicolor
88,6.3,2.3,4.4,0.1,Iris-versicolor
89,5.6,3,4.1,0.1,Iris-versicolor
90,5.5,2.5,4,0.1,Iris-versicolor
91,5.5,2.6,4.4,0.1,Iris-versicolor
92,6.1,3,4.6,0.1,Iris-versicolor
93,5.8,2.6,4,0.1,Iris-versicolor
94,5,2.3,3.3,0.1,Iris-versicolor
95,5.6,2.7,4.2,0.1,Iris-versicolor
96,5.7,3,4.2,0.1,Iris-versicolor
97,5.7,2.9,4.2,0.1,Iris-versicolor
98,6.2,2.9,4.3,0.1,Iris-versicolor
99,5.1,2.5,3,0.1,Iris-versicolor
100,5.7,2.8,4.1,0.1,Iris-versicolor
101,6.3,3.3,6,0.1,Iris-virginica
102,5.8,2.7,5.1,0.1,Iris-virginica
103,7.1,3,5.9,0.1,Iris-virginica
104,6.3,2.9,5.6,0.1,Iris-virginica
105,6.5,3,5.8,0.1,Iris-virginica
106,7.6,3,6.6,0.1,Iris-virginica
107,4.9,2.5,4.5,0.1,Iris-virginica
108,7.3,2.9,6.3,0.1,Iris-virginica
109,6.7,2.5,5.8,0.1,Iris-virginica
110,7.2,3.6,6.1,0.1,Iris-virginica
111,6.5,3.2,5.1,0.1,Iris-virginica
112,6.4,2.7,5.3,0.1,Iris-virginica
113,6.8,3,5.5,0.1,Iris-virginica
114,5.7,2.5,5,0.1,Iris-virginica
115,5.8,2.8,5.1,0.1,Iris-virginica
116,6.4,3.2,5.3,0.1,Iris-virginica
117,6.5,3,5.5,0.1,Iris-virginica
118,7.7,3.8,6.7,0.1,Iris-virginica
119,7.7,2.6,6.9,0.1,Iris-virginica
120,6,2.2,5,0.1,Iris-virginica
121,6.9,3.2,5.7,0.1,Iris-virginica
122,5.6,2.8,4.9,0.1,Iris-virginica
123,7.7,2.8,6.7,0.1,Iris-virginica
124,6.3,2.7,4.9,0.1,Iris-virginica
125,6.7,3.3,5.7,0.1,Iris-virginica
126,7.2,3.2,6,0.1,Iris-virginica
127,6.2,2.8,4.8,0.1,Iris-virginica
128,6.1,3,4.9,0.1,Iris-virginica
129,6.4,2.8,5.6,0.1,Iris-virginica
130,7.2,3,5.8,0.1,Iris-virginica
131,7.4,2.8,6.1,0.1,Iris-virginica
132,7.9,3.8,6.4,0.1,Iris-virginica
133,6.4,2.8,5.6,0.1,Iris-virginica
134,6.3,2.8,5.1,0.1,Iris-virginica
135,6.1,2.6,5.6,0.1,Iris-virginica
136,7.7,3,6.1,0.1,Iris-virginica
137,6.3,3.4,5.6,0.1,Iris-virginica
138,6.4,3.1,5.5,0.1,Iris-virginica
139,6,3,4.8,0.1,Iris-virginica
140,6.9,3.1,5.4,0.1,Iris-virginica
141,6.7,3.1,5.6,0.1,Iris-virginica
142,6.9,3.1,5.1,0.1,Iris-virginica
143,5.8,2.7,5.1,0.1,Iris-virginica
144,6.8,3.2,5.9,0.1,Iris-virginica
145,6.7,3.3,5.7,0.1,Iris-virginica
146,6.7,3,5.2,0.1,Iris-virginica
147,6.3,2.5,5,0.1,Iris-virginica
148,6.5,3,5.2,0.1,Iris-virginica
149,6.2,3.4,5.4,0.1,
150,NULL,3,5.1,0.1,Iris-virginica

In [31]:
%missing

,missing,percent
Id,0,0.00
SepalLengthCm,2,1.33
SepalWidthCm,3,2.00
PetalLengthCm,1,0.67
PetalWidthCm,0,0.00
Species,2,1.33

In [32]:
%dropmissing mode=preview

PREVIEW: would drop 8 row(s) (from 150 to 142).

Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,_would_be_dropped
7,4.6,NaN,1.4,0.3,Iris-setosa,True
14,4.3,3.0,1.1,0.1,NaN,True
17,5.4,NaN,1.3,0.1,Iris-setosa,True
28,NaN,3.5,1.5,0.1,Iris-setosa,True
31,4.8,3.1,NaN,0.1,Iris-setosa,True
37,5.5,NaN,1.3,0.1,Iris-setosa,True
149,6.2,3.4,5.4,0.1,NaN,True
150,NaN,3.0,5.1,0.1,Iris-virginica,True

In [34]:
%fillmissing mode=preview

PREVIEW: missing counts per column:
Id: missing=0
SepalLengthCm: missing=2
SepalWidthCm: missing=3
PetalLengthCm: missing=1
PetalWidthCm: missing=0
Species: missing=2
PREVIEW: computed fill-values (best-effort):
Id: would fill with -> 75.5 (mean via local preview)
SepalLengthCm: would fill with -> 5.847297297297298 (mean via local preview)
SepalWidthCm: would fill with -> 3.042857142857143 (mean via local preview)
PetalLengthCm: would fill with -> 3.773154362416107 (mean via local preview)
PetalWidthCm: would fill with -> 0.1093333333333333 (mean via local preview)
Species: could NOT determine fill value (not numeric; cannot compute mean locally); would skip

Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,_null_columns
7,4.6,NaN,1.4,0.3,Iris-setosa,SepalWidthCm
14,4.3,3.0,1.1,0.1,NaN,Species
17,5.4,NaN,1.3,0.1,Iris-setosa,SepalWidthCm
28,NaN,3.5,1.5,0.1,Iris-setosa,SepalLengthCm
31,4.8,3.1,NaN,0.1,Iris-setosa,PetalLengthCm
37,5.5,NaN,1.3,0.1,Iris-setosa,SepalWidthCm
149,6.2,3.4,5.4,0.1,NaN,Species
150,NaN,3.0,5.1,0.1,Iris-virginica,SepalLengthCm

In [35]:
%outliers

Outlier detection completed (non in-place). Summary:
Column 'Id': detected 0 outlier(s) using iqr.
Column 'SepalLengthCm': detected 0 outlier(s) using iqr.
Column 'SepalWidthCm': detected 4 outlier(s) using iqr.
Column 'PetalLengthCm': detected 0 outlier(s) using iqr.
Column 'PetalWidthCm': detected 11 outlier(s) using iqr.
Results stored in data['last_select_outliers'] (original data['last_select'] unchanged).

Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,Id_is_outlier,SepalLengthCm_is_outlier,SepalWidthCm_is_outlier,PetalLengthCm_is_outlier,PetalWidthCm_is_outlier
1,5.1,3.5,1.4,0.2,Iris-setosa,False,False,False,False,True
2,4.9,3.0,1.4,0.2,Iris-setosa,False,False,False,False,True
3,4.7,3.2,1.3,0.2,Iris-setosa,False,False,False,False,True
4,4.6,3.1,1.5,0.2,Iris-setosa,False,False,False,False,True
5,5.0,3.6,1.4,0.2,Iris-setosa,False,False,False,False,True
6,5.4,3.9,1.7,0.4,Iris-setosa,False,False,False,False,True
7,4.6,NaN,1.4,0.3,Iris-setosa,False,False,False,False,True
8,5.0,3.4,1.5,0.2,Iris-setosa,False,False,False,False,True
9,4.4,2.9,1.4,0.2,Iris-setosa,False,False,False,False,True
10,4.9,3.1,1.5,0.1,Iris-setosa,False,False,False,False,False
11,5.4,3.7,1.5,0.2,Iris-setosa,False,False,False,False,True
12,4.8,3.4,1.6,0.2,Iris-setosa,False,False,False,False,True
13,4.8,3.0,1.4,0.1,Iris-setosa,False,False,False,False,False
14,4.3,3.0,1.1,0.1,NaN,False,False,False,False,False
15,5.8,4.0,1.2,0.1,Iris-setosa,False,False,False,False,False
16,5.7,4.4,1.5,0.1,Iris-setosa,False,False,True,False,False
17,5.4,NaN,1.3,0.1,Iris-setosa,False,False,False,False,False
18,5.1,3.5,1.4,0.1,Iris-setosa,False,False,False,False,False
19,5.7,3.8,1.7,0.1,Iris-setosa,False,False,False,False,False
20,5.1,3.8,1.5,0.1,Iris-setosa,False,False,False,False,False
21,5.4,3.4,1.7,0.1,Iris-setosa,False,False,False,False,False
22,5.1,3.7,1.5,0.1,Iris-setosa,False,False,False,False,False
23,4.6,3.6,1.0,0.1,Iris-setosa,False,False,False,False,False
24,5.1,3.3,1.7,0.1,Iris-setosa,False,False,False,False,False
25,4.8,3.4,1.9,0.1,Iris-setosa,False,False,False,False,False
26,5.0,3.0,1.6,0.1,Iris-setosa,False,False,False,False,False
27,5.0,3.4,1.6,0.1,Iris-setosa,False,False,False,False,False
28,NaN,3.5,1.5,0.1,Iris-setosa,False,False,False,False,False
29,5.2,3.4,1.4,0.1,Iris-setosa,False,False,False,False,False
30,4.7,3.2,1.6,0.1,Iris-setosa,False,False,False,False,False
31,4.8,3.1,NaN,0.1,Iris-setosa,False,False,False,False,False
32,5.4,3.4,1.5,0.1,Iris-setosa,False,False,False,False,False
33,5.2,4.1,1.5,0.1,Iris-setosa,False,False,True,False,False
34,5.5,4.2,1.4,0.1,Iris-setosa,False,False,True,False,False
35,4.9,3.1,1.5,0.1,Iris-setosa,False,False,False,False,False
36,5.0,3.2,1.2,0.1,Iris-setosa,False,False,False,False,False
37,5.5,NaN,1.3,0.1,Iris-setosa,False,False,False,False,False
38,4.9,3.1,1.5,0.1,Iris-setosa,False,False,False,False,False
39,4.4,3.0,1.3,0.1,Iris-setosa,False,False,False,False,False
40,5.1,3.4,1.5,0.1,Iris-setosa,False,False,False,False,False
41,5.0,3.5,1.3,0.1,Iris-setosa,False,False,False,False,False
42,4.5,2.3,1.3,0.1,Iris-setosa,False,False,False,False,False
43,4.4,3.2,1.3,0.1,Iris-setosa,False,False,False,False,False
44,5.0,3.5,1.6,0.1,Iris-setosa,False,False,False,False,False
45,5.1,3.8,1.9,0.1,Iris-setosa,False,False,False,False,False
46,4.8,3.0,1.4,0.1,Iris-setosa,False,False,False,False,False
47,5.1,3.8,1.6,0.1,Iris-setosa,False,False,False,False,False
48,4.6,3.2,1.4,0.1,Iris-setosa,False,False,False,False,False
49,5.3,3.7,1.5,0.1,Iris-setosa,False,False,False,False,False
50,5.0,3.3,1.4,0.1,Iris-setosa,False,False,False,False,False
51,7.0,3.2,4.7,0.1,Iris-versicolor,False,False,False,False,False
52,6.4,3.2,4.5,0.1,Iris-versicolor,False,False,False,False,False
53,6.9,3.1,4.9,0.1,Iris-versicolor,False,False,False,False,False
54,5.5,2.3,4.0,0.1,Iris-versicolor,False,False,False,False,False
55,6.5,2.8,4.6,0.1,Iris-versicolor,False,False,False,False,False
56,5.7,2.8,4.5,0.1,Iris-versicolor,False,False,False,False,False
57,6.3,3.3,4.7,0.1,Iris-versicolor,False,False,False,False,False
58,4.9,2.4,3.3,0.1,Iris-versicolor,False,False,False,False,False
59,6.6,2.9,4.6,0.1,Iris-versicolor,False,False,False,False,False
60,5.2,2.7,3.9,0.1,Iris-versicolor,False,False,False,False,False
61,5.0,2.0,3.5,0.1,Iris-versicolor,False,False,True,False,False
62,5.9,3.0,4.2,0.1,Iris-versicolor,False,False,False,False,False
63,6.0,2.2,4.0,0.1,Iris-versicolor,False,False,False,False,False
64,6.1,2.9,4.7,0.1,Iris-versicolor,False,False,False,False,False
65,5.6,2.9,3.6,0.1,Iris-versicolor,False,False,False,False,False
66,6.7,3.1,4.4,0.1,Iris-versicolor,False,False,False,False,False
67,5.6,3.0,4.5,0.1,Iris-versicolor,False,False,False,False,False
68,5.8,2.7,4.1,0.1,Iris-versicolor,False,False,False,False,False
69,6.2,2.2,4.5,0.1,Iris-versicolor,False,False,False,False,False
70,5.6,2.5,3.9,0.1,Iris-versicolor,False,False,False,False,False
71,5.9,3.2,4.8,0.1,Iris-versicolor,False,False,False,False,False
72,6.1,2.8,4.0,0.1,Iris-versicolor,False,False,False,False,False
73,6.3,2.5,4.9,0.1,Iris-versicolor,False,False,False,False,False
74,6.1,2.8,4.7,0.1,Iris-versicolor,False,False,False,False,False
75,6.4,2.9,4.3,0.1,Iris-versicolor,False,False,False,False,False
76,6.6,3.0,4.4,0.1,Iris-versicolor,False,False,False,False,False
77,6.8,2.8,4.8,0.1,Iris-versicolor,False,False,False,False,False
78,6.7,3.0,5.0,0.1,Iris-versicolor,False,False,False,False,False
79,6.0,2.9,4.5,0.1,Iris-versicolor,False,False,False,False,False
80,5.7,2.6,3.5,0.1,Iris-versicolor,False,False,False,False,False
81,5.5,2.4,3.8,0.1,Iris-versicolor,False,False,False,False,False
82,5.5,2.4,3.7,0.1,Iris-versicolor,False,False,False,False,False
83,5.8,2.7,3.9,0.1,Iris-versicolor,False,False,False,False,False
84,6.0,2.7,5.1,0.1,Iris-versicolor,False,False,False,False,False
85,5.4,3.0,4.5,0.1,Iris-versicolor,False,False,False,False,False
86,6.0,3.4,4.5,0.1,Iris-versicolor,False,False,False,False,False
87,6.7,3.1,4.7,0.1,Iris-versicolor,False,False,False,False,False
88,6.3,2.3,4.4,0.1,Iris-versicolor,False,False,False,False,False
89,5.6,3.0,4.1,0.1,Iris-versicolor,False,False,False,False,False
90,5.5,2.5,4.0,0.1,Iris-versicolor,False,False,False,False,False
91,5.5,2.6,4.4,0.1,Iris-versicolor,False,False,False,False,False
92,6.1,3.0,4.6,0.1,Iris-versicolor,False,False,False,False,False
93,5.8,2.6,4.0,0.1,Iris-versicolor,False,False,False,False,False
94,5.0,2.3,3.3,0.1,Iris-versicolor,False,False,False,False,False
95,5.6,2.7,4.2,0.1,Iris-versicolor,False,False,False,False,False
96,5.7,3.0,4.2,0.1,Iris-versicolor,False,False,False,False,False
97,5.7,2.9,4.2,0.1,Iris-versicolor,False,False,False,False,False
98,6.2,2.9,4.3,0.1,Iris-versicolor,False,False,False,False,False
99,5.1,2.5,3.0,0.1,Iris-versicolor,False,False,False,False,False
100,5.7,2.8,4.1,0.1,Iris-versicolor,False,False,False,False,False
101,6.3,3.3,6.0,0.1,Iris-virginica,False,False,False,False,False
102,5.8,2.7,5.1,0.1,Iris-virginica,False,False,False,False,False
103,7.1,3.0,5.9,0.1,Iris-virginica,False,False,False,False,False
104,6.3,2.9,5.6,0.1,Iris-virginica,False,False,False,False,False
105,6.5,3.0,5.8,0.1,Iris-virginica,False,False,False,False,False
106,7.6,3.0,6.6,0.1,Iris-virginica,False,False,False,False,False
107,4.9,2.5,4.5,0.1,Iris-virginica,False,False,False,False,False
108,7.3,2.9,6.3,0.1,Iris-virginica,False,False,False,False,False
109,6.7,2.5,5.8,0.1,Iris-virginica,False,False,False,False,False
110,7.2,3.6,6.1,0.1,Iris-virginica,False,False,False,False,False
111,6.5,3.2,5.1,0.1,Iris-virginica,False,False,False,False,False
112,6.4,2.7,5.3,0.1,Iris-virginica,False,False,False,False,False
113,6.8,3.0,5.5,0.1,Iris-virginica,False,False,False,False,False
114,5.7,2.5,5.0,0.1,Iris-virginica,False,False,False,False,False
115,5.8,2.8,5.1,0.1,Iris-virginica,False,False,False,False,False
116,6.4,3.2,5.3,0.1,Iris-virginica,False,False,False,False,False
117,6.5,3.0,5.5,0.1,Iris-virginica,False,False,False,False,False
118,7.7,3.8,6.7,0.1,Iris-virginica,False,False,False,False,False
119,7.7,2.6,6.9,0.1,Iris-virginica,False,False,False,False,False
120,6.0,2.2,5.0,0.1,Iris-virginica,False,False,False,False,False
121,6.9,3.2,5.7,0.1,Iris-virginica,False,False,False,False,False
122,5.6,2.8,4.9,0.1,Iris-virginica,False,False,False,False,False
123,7.7,2.8,6.7,0.1,Iris-virginica,False,False,False,False,False
124,6.3,2.7,4.9,0.1,Iris-virginica,False,False,False,False,False
125,6.7,3.3,5.7,0.1,Iris-virginica,False,False,False,False,False
126,7.2,3.2,6.0,0.1,Iris-virginica,False,False,False,False,False
127,6.2,2.8,4.8,0.1,Iris-virginica,False,False,False,False,False
128,6.1,3.0,4.9,0.1,Iris-virginica,False,False,False,False,False
129,6.4,2.8,5.6,0.1,Iris-virginica,False,False,False,False,False
130,7.2,3.0,5.8,0.1,Iris-virginica,False,False,False,False,False
131,7.4,2.8,6.1,0.1,Iris-virginica,False,False,False,False,False
132,7.9,3.8,6.4,0.1,Iris-virginica,False,False,False,False,False
133,6.4,2.8,5.6,0.1,Iris-virginica,False,False,False,False,False
134,6.3,2.8,5.1,0.1,Iris-virginica,False,False,False,False,False
135,6.1,2.6,5.6,0.1,Iris-virginica,False,False,False,False,False
136,7.7,3.0,6.1,0.1,Iris-virginica,False,False,False,False,False
137,6.3,3.4,5.6,0.1,Iris-virginica,False,False,False,False,False
138,6.4,3.1,5.5,0.1,Iris-virginica,False,False,False,False,False
139,6.0,3.0,4.8,0.1,Iris-virginica,False,False,False,False,False
140,6.9,3.1,5.4,0.1,Iris-virginica,False,False,False,False,False
141,6.7,3.1,5.6,0.1,Iris-virginica,False,False,False,False,False
142,6.9,3.1,5.1,0.1,Iris-virginica,False,False,False,False,False
143,5.8,2.7,5.1,0.1,Iris-virginica,False,False,False,False,False
144,6.8,3.2,5.9,0.1,Iris-virginica,False,False,False,False,False
145,6.7,3.3,5.7,0.1,Iris-virginica,False,False,False,False,False
146,6.7,3.0,5.2,0.1,Iris-virginica,False,False,False,False,False
147,6.3,2.5,5.0,0.1,Iris-virginica,False,False,False,False,False
148,6.5,3.0,5.2,0.1,Iris-virginica,False,False,False,False,False
149,6.2,3.4,5.4,0.1,NaN,False,False,False,False,False
150,NaN,3.0,5.1,0.1,Iris-virginica,False,False,False,False,False

In [36]:
%clipoutliers mode=preview

PREVIEW (local): would modify 15 value(s) across 5 column(s).
Column 'Id': would clip 0 value(s) locally (bounds: -73.5, 224.5).
Column 'SepalLengthCm': would clip 0 value(s) locally (bounds: 3.1499999999999986, 8.350000000000001).
Column 'SepalWidthCm': would clip 4 value(s) locally (bounds: 2.05, 4.05).
Column 'PetalLengthCm': would clip 0 value(s) locally (bounds: -3.649999999999999, 10.349999999999998).
Column 'PetalWidthCm': would clip 11 value(s) locally (bounds: 0.1, 0.1).

Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,_oob_columns
1,5.1,3.5,1.4,0.2,Iris-setosa,PetalWidthCm
2,4.9,3.0,1.4,0.2,Iris-setosa,PetalWidthCm
3,4.7,3.2,1.3,0.2,Iris-setosa,PetalWidthCm
4,4.6,3.1,1.5,0.2,Iris-setosa,PetalWidthCm
5,5.0,3.6,1.4,0.2,Iris-setosa,PetalWidthCm
6,5.4,3.9,1.7,0.4,Iris-setosa,PetalWidthCm
7,4.6,NaN,1.4,0.3,Iris-setosa,PetalWidthCm
8,5.0,3.4,1.5,0.2,Iris-setosa,PetalWidthCm
9,4.4,2.9,1.4,0.2,Iris-setosa,PetalWidthCm
11,5.4,3.7,1.5,0.2,Iris-setosa,PetalWidthCm
12,4.8,3.4,1.6,0.2,Iris-setosa,PetalWidthCm
16,5.7,4.4,1.5,0.1,Iris-setosa,SepalWidthCm
33,5.2,4.1,1.5,0.1,Iris-setosa,SepalWidthCm
34,5.5,4.2,1.4,0.1,Iris-setosa,SepalWidthCm
61,5.0,2.0,3.5,0.1,Iris-versicolor,SepalWidthCm

In [ ]:
%encode